modLoader="javafml" #mandatory
loaderVersion="[32,)"
issueTrackerURL="https://github.com/WaterSinkingsTone/Nutrition-Revolution/issues" #optional

[[mods]]
modId="nutrirevo"
version="${file.jarVersion}"
displayName="Nutrition Revolution"
updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/WaterSinkingsTone/Nutrition-Revolution" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Relly Start" #optional
# A text field displayed in the mod UI
authors="Water Sinking Stone" #optional
description='''This is a long form description of the mod'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
